### ISSUE TITLE
error closing tags

### ISSUE THREAD

**Issue by SHIVANIUM-GIT** [RyanZim/EJS-Lint#112]
please help me  at the end of the project I got the error 

please help me 
@RyanZim 
https://drive.google.com/file/d/1Q4--4pH5Jcfecw1bNTtR4M_t4Pag_bI0/view?usp=sharing

please help me

**Comment by RyanZim** [comment]
It isn't clear to me if you're just posting about a problem you have with EJS, if you've actually used EJS-Lint, or if you're having a problem with EJS-Lint. Please try running EJS-Lint on the template in question: https://github.com/RyanZim/EJS-Lint#cli

**Comment by RyanZim** [comment]
Closing for lack of response.
