### ISSUE TITLE
Add support for asynchronous rendering

### ISSUE THREAD

**Issue by TheDogHusky** [RyanZim/EJS-Lint#131]
I'm using EJS with asynchronous rendering (passed the async: true option) and importing parts with:
```
<%- await include("parts/navbar.ejs"); %>
```

EJS lint is now unusable as it keeps telling me 
```
Unexpected token (4:16) in views/dash/edit-application.ejs
    <%- await include('parts/headers.ejs'); %>
                        ^
```
Which is completely unrevealent and prevents me from parsing other errors.

**Comment by RyanZim** [comment]
You need to pass the `--await` option for this.
