### ISSUE TITLE
New release 2.0.1 anytime soon?

### ISSUE THREAD

**Issue by pano9000** [RyanZim/EJS-Lint#133]
Hi,

The currently latest released version 2.0.0 is still depending on a vulnerable ejs version, which is why `npm audit` is screaming at me.
The affected `ejs` version was updated in the "package.json" of the main branch here already, but there hasn't been any release of `ejs-lint` since then.

Are there any plans to have a 2.0.1 version anytime soon? :-)

Thanks in advance!

**Comment by RyanZim** [comment]
Released: https://github.com/RyanZim/EJS-Lint/releases/tag/2.0.1
