### ISSUE TITLE
Feature request: set non-zero exit status if one or more lint errors

### ISSUE THREAD

**Issue by escattone** [RyanZim/EJS-Lint#18]
First of all, thanks for this project! We're going to use it for linting our [EJS templates](https://github.com/mozilla/kumascript/tree/master/macros) which are part of [MDN](https://developer.mozilla.org/en-US/) (see https://github.com/mozilla/kumascript/pull/152).

We have one request though. It'd be nice if the exit status from ``cli.js`` would be set to a non-zero value on one or more lint errors, so we can use it to make pass/fail decisions. Is this something you all are planning on adding? If not, would you be willing to consider a PR if I submit one?

Cheers!

**Comment by RyanZim** [comment]
@escattone I'm fine with changing the default behavior here. I'll fix this tonight if I can.

BTW, high five for providing MDN; it's ~a great~ **the** resource for JS!

**Comment by escattone** [comment]
Awesome, thanks so much @RyanZim!

**Comment by RyanZim** [comment]
Sorry, not happening tonight. Looking at the code, I'm realizing this needs a serious refactor. Will try to do ASAP though.

**Comment by escattone** [comment]
No worries, thanks again.

**Comment by RyanZim** [comment]
Fixed in v0.3.0: https://github.com/RyanZim/EJS-Lint/releases/tag/v0.3.0 :tada:

**Comment by escattone** [comment]
Thanks so much @RyanZim !

**Comment by RyanZim** [comment]
Note that you'll need to upgrade to v0.3.0 for this change. https://github.com/mozilla/kumascript/blob/master/package.json#L27
