### ISSUE TITLE
Not catching certian errors

### ISSUE THREAD

**Issue by codejamninja** [RyanZim/EJS-Lint#44]
ejs-lint does not recognize the following as an error, but ejs throws an error.

Any reason why ejs-lint doesn't think that is a problem?

```ejs
<% hello =>
```

**Comment by RyanZim** [comment]
EJS-Lint only catches errors in your JS inside your valid script tags. PR welcome to expand it to catch more. Closing since this a basically a dupe of https://github.com/RyanZim/EJS-Lint/issues/32.

**Comment by codejamninja** [comment]
Ah, thanks
