### ISSUE TITLE
how to use ejs-lint

### ISSUE THREAD

**Issue by samuelguesnier** [RyanZim/EJS-Lint#46]
When installed, how to run the cli ? I tried in the terminal "ejslint myfilename.ejs" but it doesn't work it just says command not found.

**Comment by RyanZim** [comment]
Did you install globally? `npm install -g ejs-lint`

**Comment by samuelguesnier** [comment]
Ho yes it works, thank you Ryan. But I got this error 

"SyntaxError: Unexpected token else in traitement.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint"
So I tried  ejs lint but it's  not detecting any error.

Here is the code, it seems there is  problem with the "else": 
`<% for (let attr in attributsCircuit){ %>
                <% if (typeof circuit1.attr !== 'undefined'){ %>
                <td><%= circuit1.attribut %></td>
                <% } %>
                <% else { %>
                <td></td>
                <% } %>
                <% } %>`

**Comment by samuelguesnier** [comment]
probleme solved, } has to be paired, thank you :)

**Comment by Tian9000** [comment]
I have the same problem, but I don't know how to use it ?? Please explain to me??

**Comment by alishanAfridi** [comment]
npm install -g ejs-lint
