### ISSUE TITLE
ejs lint says "Unexpected token (14:8)"

### ISSUE THREAD

**Issue by CityOnTheEdgeOfForever** [RyanZim/EJS-Lint#48]
what does Unexpected token (14:8) mean? I thought 14 refers to row, and 8 refers to char count from left, but it's not.

Thanks.

**Comment by RyanZim** [comment]
It should refer to `row:column`. Can you post your EJS file?

**Comment by CityOnTheEdgeOfForever** [comment]
Ryan, thanks for the response. I figured out the issue by looking at the code!
