### ISSUE TITLE
missing ) after argument list "location to site" while compiling ejs

### ISSUE THREAD

**Issue by kohli6010** [RyanZim/EJS-Lint#65]
I am unable to include partials in ejs

**Comment by kohli6010** [comment]
it actually location to file

**Comment by RyanZim** [comment]
I'm not understanding your issue?

**Comment by kohli6010** [comment]
basically when I am including a partial it is giving me missing ) in argument list error

**Comment by RyanZim** [comment]
Well, that means you missed a closing parenthesis someplace
