### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by Mustafiz04** [RyanZim/EJS-Lint#69]
Unexpected identifier in F:\coding\CWeb\views\home.ejs while compiling ejs

I'm getting this error, even I had read this repo but I didn't get yet. please help me to resolve this issue.

**Comment by RyanZim** [comment]
Are you getting this error from ejs or ejs-lint?

**Comment by Mustafiz04** [comment]
error from ejs. how to use ejs-lint?

**Comment by RyanZim** [comment]
`npm install -g ejs-lint` to install; then `ejslint <filename>` to check the file that's causing the error.
