### ISSUE TITLE
show the offending line and character in context?

### ISSUE THREAD

**Issue by kenirwin** [RyanZim/EJS-Lint#70]
I would love it if EJS-Lint would return not just the line/character number of the error, but also show the error in context. Something like this: 
<img width="942" alt="example" src="https://user-images.githubusercontent.com/1894561/78596083-29431880-7819-11ea-8adc-1c61c60a0e6c.png">

The output above is from a shell script I wrote to post-process EJS-Lint errors: 
https://github.com/kenirwin/ejshint
But it's a super-simple script that probably can't handle the complexity of multiple errors etc. 

If this is something you'd be interested in having in EJS-Lint but are not pursuing right now, I'd be interested in working up a pull request. I'd be glad for some pointers about where to start in the code to do it in a way you'd like to see. Please let me know what you think. Thanks!

**Comment by RyanZim** [comment]
I'd be fine with doing this. Of course, It'd have to be done in pure Node.js (no shell scripting). Here's the bit that prints the error messages currently: https://github.com/RyanZim/EJS-Lint/blob/bff632f5c5e6352c735d8b10cf62d8a6580ac5ad/cli.js#L34-L36

That would need to be modified. Also, the tests would need to be updated to ensure this new behavior is tested properly. If you want to take a stab at it, PR welcome!

**Comment by kenirwin** [comment]
Thanks @RyanZim -- I'll see what I can come up with. A pure Node/built-in solutions seems preferable to yesterday's hack for sure!
