### ISSUE TITLE
ejs-lint from Windows terminal??

### ISSUE THREAD

**Issue by adambu** [RyanZim/EJS-Lint#74]
I installed ejs-lint globally and ran like this:
ejslint .\src\views\blog-single-test.ejs

I just sits there.  No error of any kind.  I notice there is ejslint.cmd in my path.  How do you run on windows?  Surely, this has come up before, but I don't see any instructions indicating any difference for windows.

**Comment by RyanZim** [comment]
Looks like somehow, it's not understanding the path you're passing in, and is trying to read from stdin, in which case it will hang as described. Exactly what's happening is hard to know.

**Comment by adambu** [comment]
I posted on Gitter after doing some more research.  Please see my very recent post.

Best regards,

Adam Burns
Sr. Support Escalation Engineer - SharePoint development
Email: adambu@microsoft.com<mailto:adambu@microsoft.com>
Phone:   425-707-2428
Hours:  8:00am-7:00pm Pacific M - F

**Comment by RyanZim** [comment]
ejs-lint is not associated with eslint in any way.

I am not sure why this isn't working on Powershell; it should work. Maybe try without the leading `.\`? IDK, not very familiar with Windows.

**Comment by souvik362** [comment]
i think i have the solution just change the directory  to the views folder and ejs lint like this -
`cd views && ejslint <fileNamewithEjsExt`
Just make sure you are on view folder
