### ISSUE TITLE
SyntaxError: Unexpected token '.'<adress>while compiling ejs

### ISSUE THREAD

**Issue by ibandim123** [RyanZim/EJS-Lint#78]
### Hi, i have some trouble here, i received this message error : "SyntaxError: Unexpected token '.' in C:\Users\USUARIO\Documents\Project Web\Eventosapp\src\views\contatos\index.ejs while compiling ejs"### 

  In views, this docs : 
*contatos
*Home
*exit.ejs
*footer.ejs
*header.ejs

**My idea is import "partials" from one for the another, using ejs! please some help me**

code below
views\contatos\index.ejs

`<% include ../header %>
<header>
    <h1>Petrolina Party</h1>
    <h4>Lista de Contatos</h4>
</header>
<section>
    <p>Bem vindo <%- usuario.nome %></p>
</section>
<% include ../exit%>
<% include ../footer %>`

**Comment by RyanZim** [comment]
If you're using EJS v3; you can't use `include <file>`, you have to use `include(<file>)`; see EJS docs for details. If you're actually using EJS v2; pass the `--preprocessor-include` CLI flag to EJS-Lint

**Comment by ibandim123** [comment]
Thank so much, Ryan,!!
