### ISSUE TITLE
Pass options to acorn via 'options'

### ISSUE THREAD

**Issue by daedal-knickerbockers** [RyanZim/EJS-Lint#81]
# Pass options to acorn via `options`

This would allow successful linting of ejs templates using async / await.

## Problem

The following template will return an `Unexpected Token` error from ejs-lint. However, ejs explicitly allows usage of root-level await.

```ejs
<%- await foo() %>
```

## Solution

Being able to pass acorn options when linting the template would solve this issue:

```javascript
ejsLint(template, { allowAwaitOutsideFunction: true });  // Now lints without problem
```

The needed change itself is pretty small - I forked the project and implemented it [here](https://github.com/daedal-knickerbockers/EJS-Lint/commit/8ab32d1ff2dacb45be2fb81f567f557b1c2f6af7), maybe you can have a look?

Would this be something you would consider a feature yourself, too? Any feedback is welcome 😄

**Comment by RyanZim** [comment]
I'd prefer if we'd add an option to `EJS-Lint` itself, `await`, that would turn on `allowAwaitOutsideFunction` in `acorn`, but not allow passing arbitrary options to `acorn`.
