### ISSUE TITLE
how to produce output of .ejs file to html without any data_file

### ISSUE THREAD

**Issue by programerr01** [RyanZim/EJS-Lint#85]
```bash 
ejs main.ejs  -o ./output.html
```
this is the command that i am using

**Comment by RyanZim** [comment]
This is a question for https://github.com/mde/ejs, not EJS-Lint. That said, I'll try to answer briefly here:

You would need to use the `-i` option; from the [docs](https://github.com/mde/ejs#cli):

> `-i / --data-input STRING` Must be JSON-formatted and URI-encoded. Use parsed input from STRING as data for rendering.
