### ISSUE TITLE
EJS-lint hangs with invalid file path

### ISSUE THREAD

**Issue by YZirkind** [RyanZim/EJS-Lint#86]
Context: I'm running EJS-lint on Windows; Windows' path delimiter is a backwards-slash (e.g. `C:\path\to\file.ext`).

EJS-lint uses [`globby`](https://github.com/sindresorhus/globby) to generate a list of files from the paths provided as arguments. This is not mentioned in `usage`, nor in the Readme. Because `globby` doesn't support backward-slashes, when I pass in Windows path (e.g. `views\index.ejs`), it returns an empty array. So this:
https://github.com/RyanZim/EJS-Lint/blob/b5ee5a2969700a83f100933bedfbb5806f4da84c/cli.js#L33
becomes:
```
    read([])
```
which never resolves, because [`read` will then wait for stdin](https://github.com/rstacruz/read-input/blob/69fb58fdab1f176d3158fd3fcf086f7afda8c510/index.js#L39).

I would suggest documenting this, or using something like [`slash`](https://github.com/sindresorhus/slash) (by the developer of `globby`) to process the file paths before passing them into `globby`.

**Comment by RyanZim** [comment]
Good point, PR welcome to add `slash`.
