### ISSUE TITLE
Syntax-Check inside <%= and <%-

### ISSUE THREAD

**Issue by cyberwombat** [RyanZim/EJS-Lint#9]
Given a tag such as `<Product_Description><%= variant.description, %></Product_Description>` (notice the trailing comma), EJS crashes with the unhelpful `[SyntaxError: Unexpected token )` while compiling ejs. However when I ran it through ejs-lint (thanks for coding that btw) it cam up with no errors.

**Comment by RyanZim** [comment]
https://github.com/RyanZim/EJS-Lint#features says:

> EJS-Lint parses scriptlet tags (`<%`, `%>`, `<%_`, `_%>`, and `-%>`). **It ignores all other tags (i.e. `<%=`).**

(emphasis added).

Since your syntax error is inside an output tag (not a scriptlet), EJS-Lint doesn't syntax-check it; and therefore does not throw an error.

I have considered syntax-checking the output expressions, but never got around to implementing it. I'm not sure what would be the best way to do this. Ideas?

**Comment by cyberwombat** [comment]
Oh I didn't realize that. yes it would be a nice option for sure. Perhaps in the parsing you could assign any print expression to a variable instead. That should concatenate to `str` nicely and cause it to fail appropriately I would think.

**Comment by RyanZim** [comment]
That would be one way. The difficulty is keeping the line & column numbers accurate. (Could be done)

I wouldn't make it an option, just default behavior.

If you want to try your hand at a PR, go ahead.

**Comment by RyanZim** [comment]
BTW, I'm not sure if node-syntax-error checks type. You might not need to use a print expression, just any function.

**Comment by TimothyGu** [comment]
@RyanZim, you can use is-expression module (written by me) to assert that a specific expression is valid JS. Then you can catch the error which contains line & col information.

**Comment by RyanZim** [comment]
@TimothyGu thanks for dropping by. I thought I had seen a module like that, but couldn't remember what it was called.

The only problem with that approach: how are we going to generate the output for `parse()`? We can remove that method if it isn't practical to keep. I just thought someone might want to use a different syntax-checker or perhaps even JSHint, etc.

**Comment by RyanZim** [comment]
@TimothyGu thoughts?

**Comment by RyanZim** [comment]
To be honest, I hardly use EJS-Lint myself, so this isn't very high on my TODO list. Feel free to make a PR. I'm fine with removing `.parse()` and using is-expression. Make sure to add tests!

**Comment by RyanZim** [comment]
`.parse()` was removed in v0.3.0, so implementing this should be much easier.
