### ISSUE TITLE
Error view change request

### ISSUE THREAD

**Issue by MMgame4** [RyanZim/EJS-Lint#93]
Hello,
I usage ejs long time.
And I would very much appreciate adding the error, line and character to the typeface to make it easier to find out where the error is.
e.g.
Current error visor: SyntaxError: missing ) after argument list in ***\views\app\index.ejs while compiling ejs
Proposed visor: SyntaxError: missing ) after argument list in ***\views\app\index.ejs while compiling ejs. In line: 2, char: 12

**Comment by RyanZim** [comment]
EJS cannot easily support better errors, if you want better errors, you should use `ejs-lint`.

**Comment by MMgame4** [comment]
Thanks
