### ISSUE TITLE
CVE from ejs@3.1.5

### ISSUE THREAD

**Issue by Abe27342** [RyanZim/EJS-Lint#94]
Hello!

My team has been using ejs-lint for a while now--thank you for this contribution!

Our component governance tooling recently flagged a [code injection vulnerability](https://snyk.io/vuln/SNYK-JS-EJS-1049328) on ejs@3.1.5. They addressed it in 3.1.6: see commit [here](https://github.com/mde/ejs/commit/abaee2be937236b1b8da9a1f55096c17dda905fd).

It may also be a good idea to specify `ejs` as a caret dependency--if done so it would have been possible to work around this on our end.

I'd be happy to open a PR to bump the dependency if that's welcomed.

Thanks!

**Comment by RyanZim** [comment]
Yeah; though the CVE doesn't affect our usage, I'm fine with upgrading to silence the alert. PR welcome.

Unfortunately, we can't use a caret dependency, since we sort of rely on some undocumented internal behavior in ejs that could be broken by a patch upgrade.
